In [2]:
import numpy as np
b = np.arange(27).reshape((3,3,3))
print(b)
id(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


82318320

In [3]:
id(b.ravel())


88605360

In [4]:
import numpy as np
x = np.arange(27).reshape((3,3,3))
print(x)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [5]:
b.flatten

<function ndarray.flatten>

In [6]:
x = np.arange(12).reshape(3,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
# x.T
np.transpose(x)





array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [11]:
a = np.arange(5)
print(a)
a <= 2


[0 1 2 3 4]


array([ True,  True,  True, False, False])

In [12]:
print(a)
(a<2) | (a>3)

[0 1 2 3 4]


array([ True,  True, False, False,  True])

In [13]:
def exp (x):
    return x<3 or x>3


np.vectorize(exp)(a)

array([ True,  True,  True, False,  True])

In [14]:
r = a<3

print(np.size(a[r]))
print(a[r].size)
r

3
3


array([ True,  True,  True, False, False])

In [18]:
s = np.arange(25)
print(s)
print(np.sum(s < 10))
print(np.sum(s[s<10]))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
10
45


In [17]:
import numpy as np

arr = np.arange(16).reshape(4, 4)

print(arr[arr %2 != 0])

np.sum(arr[arr %2 != 0])

[ 1  3  5  7  9 11 13 15]


64

In [9]:
a =  np.arange(9).reshape(3 , 3)
print(a)
b = np.arange(10,19).reshape(3,3)
print(b)
c = np.arange(20,29).reshape(3,3)
print(c)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[20 21 22]
 [23 24 25]
 [26 27 28]]


In [21]:
#np.hstack((a, b,c))
np.vstack((c, c , c))

NameError: name 'c' is not defined

In [33]:
p = [[3, 4, 6], [0, 2, 8]]
z = [[9, 7, 4], [7, 9, 7]]
#np.concatenate((p , z) , axis = 1)
np.dstack((p,z))

array([[[3, 9],
        [4, 7],
        [6, 4]],

       [[0, 7],
        [2, 9],
        [8, 7]]])

In [31]:
a=np.arange(9)
b=np.arange(10,19)
c=np.arange(19,29)

np.dstack((a , b , c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [13]:
sp = np.arange(12).reshape(3,4)

print(sp)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [14]:
np.split(sp,2 , axis = 1)



[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [15]:
x = np.array([5,6,7,1,3,10,69,55,32]).reshape(3,3)
# x = np.arange(9).reshape(3,3)
print(x)
# x.min()
# x.max()
# x.argmin()
# x.argmax()
# x.min(axis = 0)
# x.std()
# x.prod()
# (x < 10).any()
# (x>10).all()

[[ 5  6  7]
 [ 1  3 10]
 [69 55 32]]
