In [3]:
import numpy as np
x=np.array([1,2,3,4,5]) #vector
a=np.array([[1,2,3,4,5]]) #matrix
b=np.array(5) #0 dimension scalar value
print(type(x),type(a),type(b))
print(x.shape,x," ",a.shape,a," ",b.shape,b)

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
(5,) [1 2 3 4 5]   (1, 5) [[1 2 3 4 5]]   () 5


In [18]:
my_arr=np.arange(45).reshape(9,5).astype('float')
print(my_arr)
#(depth,row,column) 3dimension stack
arr_3d=np.arange(45).reshape(3,3,5)
print(arr_3d)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34.]
 [35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44.]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]]


In [4]:
#slicing of matrix
b=np.arange(24).reshape(6,4)
print(b)
newb=b[2:4,1:3]
print(newb)
a=b[4:5,2:3]
a1=b[4,2]
print(a,"<= 2 dimension matrix , ",a.ndim," ",a1,"<= scalar value  "," ",a1.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 9 10]
 [13 14]]
[[18]] <= 2 dimension matrix ,  2   18 <= scalar value     0


In [19]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
a[0:6:2]

array([0, 2, 4])

In [38]:
arr_3d=np.arange(27).reshape(3,3,3)
arr_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [43]:
new_arr_3d=arr_3d[1:2,1:3,1:2]
new_arr_3d

array([[[13],
        [16]]])

In [45]:
assignment=np.arange(75).reshape(5,3,5)
assignment

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]],

       [[45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]]])

In [49]:
qq=assignment[2:3,1:,3:]
qq

array([[[38, 39],
        [43, 44]]])

In [54]:
assignment[3:4,2:,2:3]=100
print(assignment[3:4,2:,2:3])
assignment

[[[100]]]


array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14]],

       [[ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29]],

       [[ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44]],

       [[ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56, 100,  58,  59]],

       [[ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]]])

In [61]:
div=np.linspace(1,50,6)
print(div)
di=np.arange(1,51,9.8)#b-a/n-1=50-1/6-1
print(di)

[ 1.  10.8 20.6 30.4 40.2 50. ]
[ 1.  10.8 20.6 30.4 40.2 50. ]


In [ ]:
#generate a matrix

In [65]:
np.arange(1,20,2)
np.linspace(1,19,10)


array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

In [83]:
a=np.zeros((10,10))
a[0:1,0:]=1
a[0:,0:1]=1
a[0:,9:]=1
a[9:,0:]=1
a
b=np.ones((10,10))
b[1:-1,1:-1]=0
b

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])